---
services:
  puppet:
    image: ghcr.io/voxpupuli/puppetserver:8.6.3-latest
    hostname: puppet
    environment:
      PUPPETSERVER_HOSTNAME: puppet
      PUPPETSERVER_PORT: 8140
      USE_PUPPETDB: false
      AUTOSIGN: true
    restart: always
    ports:
      - 8140:8140

networks:
  default:
    name: crafty-pps
